name: Test Suite

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Packages
        run: npm install && npm run install:all
      - name: Lint Backend
        run: npm run lint:be
      - name: Lint Frontend
        run: npm run lint:fe
      - name: Run Prettier
        run: npm run prettier:ci

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Packages
        run: npm install
        working-directory: ./backend
      - name: Test Backend
        run: npm run test
        working-directory: ./backend
