name: Test Suite

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  backend:
    name: Lint, Format, and Test Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Packages
        run: npm install
        working-directory: ./backend
      - name: Lint Backend
        run: npm run lint
        working-directory: ./backend
      - name: Run Prettier
        run: npm run format
        working-directory: ./backend
      - name: Run Tests
        run: npm run test
        working-directory: ./backend

  frontend:
    name: Lint, Format, and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Packages
        run: npm install
        working-directory: ./frontend
      - name: Lint Frontend
        run: npm run lint
        working-directory: ./frontend
      - name: Run Prettier
        run: npm run format
        working-directory: ./frontend
